linters:
  enable-all: true
  disable:
  # Noisy things that aren't useful.
  - cyclop
  - exhaustivestruct
  - exhaustruct
  - funlen
  - gomnd
  - nlreturn
  - varnamelen
  - wsl

  # Archived by owner.

  # Not yet supported in Go 1.18.

linters-settings:
  gomoddirectives:
    # Allow local `replace` directives.
    # Default: false
    replace-local: true

  exhaustive:
    # Presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed.
    # Default: false
    default-signifies-exhaustive: true

run:
  skip-dirs:
    - dupe
